name: jetleaf_web
description: Web context for JetLeaf â€” provides HTTP, routing, and client-server helpers.
version: 1.0.4

homepage: https://jetleaf.hapnium.com
repository: https://github.com/jetleaf/jetleaf_web
issue_tracker: https://github.com/jetleaf/jetleaf_web/issues
documentation: https://jetleaf.hapnium.com/docs/web

topics:
  - web
  - http
  - routing
  - jetleaf
  - client-server

keywords:
  - jetleaf
  - web
  - http
  - routing
  - server

environment:
  sdk: ^3.9.0

dependencies:
  meta: ^1.17.0
  jetleaf_lang: ^1.0.5
  jtl: ^1.0.4
  jetson: ^1.0.4
  jetleaf_logging: ^1.0.5
  jetleaf_pod: ^1.0.5
  jetleaf_core: ^1.0.5
  jetleaf_env: ^1.0.5
  jetleaf_utils: ^1.0.5

dev_dependencies:
  test: ^1.25.0
  lints: ^6.0.0